// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using src.Datos;

#nullable disable

namespace src.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("src.Modelos.Pelicula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Calificacion")
                        .HasColumnType("REAL");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Duracion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Etiquetas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Peliculas");
                });

            modelBuilder.Entity("src.Modelos.PerfilUsuario", b =>
                {
                    b.Property<string>("NombreUsuario")
                        .HasColumnType("TEXT");

                    b.Property<string>("EtiquetasPreferidas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GenerosPreferidos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdsMiLista")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdsVistos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("NombreUsuario");

                    b.ToTable("PerfilesUsuarios");
                });

            modelBuilder.Entity("src.Modelos.Recomendacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeliculaId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Puntuacion")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PeliculaId");

                    b.ToTable("Recomendaciones");
                });

            modelBuilder.Entity("src.Modelos.Recomendacion", b =>
                {
                    b.HasOne("src.Modelos.Pelicula", "Pelicula")
                        .WithMany()
                        .HasForeignKey("PeliculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pelicula");
                });
#pragma warning restore 612, 618
        }
    }
}
